name: Git Diff Conditional
description: Conditionally run steps based on git diff files
author: https://github.com/zegocover
requirements:
  - docker
configuration:
  properties:
    dynamic_pipeline:
      type: string
    disable_plugin:
      type: boolean
    diff:
      type: string
    log_level:
      type: string
    steps:
      type: [ object, array ]
      minimum: 1
      properties:
        label:
          type: string
        include:
          type: [ string, array ]
        exclude:
          type: [ string, array ]
  required:
    - dynamic_pipeline
    - steps